---
- name: "Install JDK 21 from tarball"
  hosts: all
  become: yes
  tasks:
    - name: "Download JDK 21 Tarball"
      get_url:
        url: "https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.tar.gz"
        dest: "/tmp/jdk-21_linux-x64_bin.tar.gz"
        mode: "0644"

    - name: "Extract JDK 21 Tarball to /opt"
      unarchive:
        src: "/tmp/jdk-21_linux-x64_bin.tar.gz"
        dest: "/opt"
        remote_src: true
        # creates stops re-extraction if the directory already exists:
        creates: "/opt/jdk-21"
